### ISSUE TITLE
Theme in Editor doesn't load

### ISSUE THREAD

**Issue by ProjectArctos** [handihow/skilltree#10]
I just created an account and when I try clicking on "Theme" in the editor it gives me an error reading "Could not load Google fonts". Not sure if I was supposed to do something ahead of time?

![Error screen](https://user-images.githubusercontent.com/69993878/90834121-7bdc2780-e317-11ea-99e6-760b656cf4c6.png)

**Comment by handihow** [comment]
Hi , thanks for reporting the bug.

I have fixed it and everything should be working now. Please refresh your page.
