### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by V-Arui** [handihow/skilltree#23]
Hello!

I use this tool and I thought it would be great if you could introduce a new function. It would be useful to have the option to create child skills that require 2 or more root skills to be complete. This would make it possible to illustrate tasks that require multiple prerequisites. I apologize if this feature is already present and I missed it.

Thanks,
          V. Arui

**Comment by handihow** [comment]
Hello,

nice that you are using the tool and thanks for the feature request! 

Our free and open source tool Easy-skilltree uses another open source code for the skilltree functionality:
[React beautiful skilltree](https://github.com/andrico1234/beautiful-skill-tree)

The feature should be made possible in this software first, before I can incorporate it in the web application Easy-skilltree.

Therefore, it will be better if you request the feature on that repository! If the feature is accepted, I will then include it in the web application.

It sounds like a very interesting feature! And it does not yet exist.

Cheers,

Roeland

**Comment by handihow** [comment]
It even looks like someone else requested a similar feature on BST:

https://github.com/andrico1234/beautiful-skill-tree/issues/56
