### ISSUE TITLE
Editor goes to a blank screen

### ISSUE THREAD

**Issue by ProjectArctos** [handihow/skilltree#28]
Thanks for creating this website! It's been a great tool to work with. I've recently had trouble getting the editor to work. Every time I click on the "Skilltree editor"  it starts to load and then goes to a blank screen. I tried in a few browsers (Chrome, Firefox, Edge) but it still would go blank (see attached). Do you know if this is something on my end or something on the site itself?

![screenshot](https://user-images.githubusercontent.com/69993878/116769752-99b46d00-aa0c-11eb-8074-9967d9992ce4.png)

**Comment by handihow** [comment]
thanks for pointing this out. I have picked up an error and now things should be back to normal. Please try to access the editor again, it should be working fine!

**Comment by ProjectArctos** [comment]
Working now, thanks!
