### ISSUE TITLE
Reset Button Retains Percentage

### ISSUE THREAD

**Issue by Thunderheart987** [handihow/skilltree#39]
Hello!

I was messing around with your program, however, the Reset button resets the skills as expected, but doesn't reset the percentage. As such, the percentage continues to rise, making it inaccurate.
Manually clicking the skill lowers the percentage normally.
![ResetButtonIncorrect](https://user-images.githubusercontent.com/89104856/129796234-bd5d51e8-66ea-49b6-b835-e1d202a20c26.png)

**Comment by handihow** [comment]
Hi, thanks for bringing up this issue.
I have managed to reproduce the bug. At the same time, I found that it would be better to ask the user confirm before resetting the skills completion state. 
Now you will see that on hitting the reset button, you will first get a notification window asking you to confirm or cancel. When cancelling, your skilltree will not be reset. If you do however confirm, the skilltree resets and the percentage is also reset to 0% as it should.
