### ISSUE TITLE
Large trees' skills disappearing screen right

### ISSUE THREAD

**Issue by S1vaLing4m** [handihow/skilltree#4]
Larger trees' skills are not fitting on the screen, with no ability to scroll over to the right to view

**Comment by S1vaLing4m** [comment]
Note: This issue only happens in the viewer inside the editor

**Comment by handihow** [comment]
thanks, I have reproduced the issue, and will work on a fix

**Comment by handihow** [comment]
I uploaded a fix now. You should be able to scroll right when there is overflow on a large tree.

By the way, you may find options in the Theme customizer to improve the tree.

For example, you could choose a different font that is narrower, or set the node size to narrow, or set the font size to small. Or do all these things. They will make your tree width smaller overall.

You can just use the provided credit card number if you want to unlock all the features, we are still in testing phase so everything is free of charge.

<img width="1440" alt="Schermafbeelding 2020-04-02 om 20 11 20" src="https://user-images.githubusercontent.com/46277832/78283741-893a7600-751e-11ea-809b-f7607b760ed4.png">
