### ISSUE TITLE
Mac compatible?

### ISSUE THREAD

**Issue by S1vaLing4m** [handihow/skilltree#5]
Users trying to access the viewer for one of my skilltrees on Mac devices report that it is coming up blank, on iPhone and Mac, using either Safari or Firefox. Is the application Mac compatible?

**Comment by handihow** [comment]
There was an issue with a package in the application, causing an error in Safari / Firefox. I have traced down the issue and uploaded an improved version that works in Safari and Firefox.
I have just tested this and it works, please tell your users to try again, it should work as expected now.

**Comment by S1vaLing4m** [comment]
Yes it works perfectly now, thank you!
